name: codem
channels:
  - conda-forge
dependencies:
  - python-pdal
  - opencv
  - rasterio
  - trimesh
  - matplotlib
  - scikit-image
  - rich
  - numpy
  - typing-extensions
  - gdal
  - pyproj
  - pyshp
  - pandas
  - pyarrow
